echo "--------------------------------------------------"
echo "Monster Trading Cards Game"
echo "--------------------------------------------------"
echo "CURL Testing for Monster Trading Cards Game"
echo ""
echo "1) Messages"
echo "1.1) Create messages"
curl -X POST http://localhost:8080/messages --header "Content-Type: application/json" -d "{\"message\":\"Eine neue Nachricht\"}"
echo ""
curl -X POST http://localhost:8080/messages --header "Content-Type: application/json" -d "{\"message\":\"Eine weitere Nachricht\"}"
echo ""
echo "1.2) List all messages"
curl http://localhost:8080/messages
echo ""
echo "1.3) List message with ID 1"
curl http://localhost:8080/messages/1
echo ""
echo "1.4) Update message with ID 1"
curl -X PUT http://localhost:8080/messages/1 --header "Content-Type: application/json" -d "{\"message\":\"Eine neue Nachricht 2.0\"}"
echo ""
curl http://localhost:8080/messages/1
echo ""
echo "1.5) Delete message with ID 1"
curl -X DELETE http://localhost:8080/messages/1
echo ""
echo "Should return Not Found:"
curl http://localhost:8080/messages/1
echo ""
echo ""
echo "2) Users"
echo "2.1) Create users"
curl -X POST http://localhost:8080/users --header "Content-Type: application/json" -d "{\"username\":\"schrom\",\"password\":\"moritz\"}"
echo ""
curl -X POST http://localhost:8080/users --header "Content-Type: application/json" -d "{\"username\":\"kienboec\",\"password\":\"daniel\"}"
echo ""
curl -X POST http://localhost:8080/users --header "Content-Type: application/json" -d "{\"username\":\"altenhof\",\"password\":\"markus\"}"
echo ""
echo "Should fail (duplicate username):"
curl -X POST http://localhost:8080/users --header "Content-Type: application/json" -d "{\"username\":\"schrom\",\"password\":\"password\"}"
echo ""
echo "2.2) Login"
TOKEN=$(curl -s -X POST http://localhost:8080/login --header "Content-Type: application/json" -d "{\"username\":\"schrom\",\"password\":\"moritz\"}")
echo "Login successful, got token: ${TOKEN//\"}"
echo "Should fail (wrong password):"
curl -X POST http://localhost:8080/login --header "Content-Type: application/json" -d "{\"username\":\"schrom\",\"password\":\"password\"}"
echo ""
echo "2.3) Get user with ID 1"
echo "Should fail (not authenticated)"
curl http://localhost:8080/users/1
echo ""
echo "Should succeed (authenticated)"
curl http://localhost:8080/users/1 --header "Content-Type: application/json" --header "Authorization: Basic ${TOKEN//\"}"
echo "Should fail (authenticated but not authorized)"
curl http://localhost:8080/users/2 --header "Content-Type: application/json" --header "Authorization: Basic ${TOKEN//\"}"
echo "2.4) Delete user with ID 2"
TOKEN2=$(curl -s -X POST http://localhost:8080/login --header "Content-Type: application/json" -d "{\"username\":\"kienboec\",\"password\":\"daniel\"}")
echo "Login successful, got token: ${TOKEN2//\"}"
echo "Should fail (not authenticated)"
curl -X DELETE http://localhost:8080/users/2
echo "Should fail (authenticated but not authorized)"
curl -X DELETE http://localhost:8080/users/2 --header "Authorization: Basic ${TOKEN//\"}"
echo "Should succeed (authenticated)"
curl -X DELETE http://localhost:8080/users/2 --header "Authorization: Basic ${TOKEN2//\"}"
